### ISSUE TITLE
Beta

### ISSUE THREAD

**Issue by lastmjs** [lastmjs/podcrypt#12]
- [x] How do I know that I'm ready to release the beta? Consider this: Podcrypt should be relatively feature-complete for the MVP by the end of alpha. Beta should be improving the existing features, fixing bugs, adding tests, etc. In fact, I think that all of the automated test stuff that I mention here, along with improving code refactoring, css, etc should be pushed off into the beta. I need to get the features out there for alpha. I need to get to beta as fast as possible. Improving those features is what the alpha should be for. Do not do anything that is not necessary for the MVP during alpha. Lock down the feature-set, implement the features, then push out the beta.
- [x] The slider disappears at the right and starts a little too far past the left
- [x] Protect against bad mnemonic phrases, ask the user to confirm (I don't ask the user to confirm, but I do make sure the phrase is twelve words)
- [x] Playlist went to the loading page on Rob mcnealy show for some reason when it was having a hard time loading...fixing the router prop changes will probably help fix that
- [x] Create a TheGraph Subgraph for Podcrypt
- [x] Get on all of the DApp tracking websites
- [x] Finish completely refactoring the wallet and all of its components with the new design style and css
- [x] For background playlist progression, try playing multiple audio elements at once, each element except for the main one will play silence. The silence will be as long as all of the audio element sources before it. Then we can progress in the background, because we will always be playing and never stop
- [x] Follow Android playlist in the background on cellular data issues:https://bugs.chromium.org/p/chromium/issues/detail?id=884517&can=2&start=0&num=100&q=Media%20notification&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=
- [x] Podcast downloads
- [x] Subscribe to podcasts
- [x] Offline capabilities (service workers), install to homescreen, PWA features
- [x] Interval can be changed
- [x] Powerful podcast search
- [x] Percentages to pay out can be changed
- [x] Value per unit of time can be changed
- [x] Use web.dev as a resource to audit everything
- [x] Automated tests, mostly for the time tracking and payments
- [x] Entities to receive payouts can be turned on or off before the interval is over
- [x] Explain security
- [x] Relatively beautiful UI
- [x] Looks good on desktop
- [x] Starts and stops need to be robust...what if you never have a stop event? Right now, if there are multiple starts, all previous starts are ignored...lame, potentially
 - [x] Perhaps when making a start timestamp, if the previous timestamp is not undefined or stop, insert one a stop timestamp...then, the list can heal itself
- [x] Make sure all font sizes are perfectly responsive
- [x] Make sure scrolling is smooth, it seems to jank a bit and stop, then allow you to scroll more on some of the lists
- [x] Make a row item component potentially...there seem to be similarities between all of our row items, extreme similarities, css, html structure, etc
- [x] Standardize z-indeces
- [x] Use the new technique from the main menu for loading each element...individually, each element should take care of their own loading I am thinking
- [x] Debit card purchases with Wyre
- [x] Get RSSParser to be a module that runs without build tools (except bare specifiers)
- [x] Study how MetaMask handles private keys...the web3 docs say to never store the private key unencrypted in localStorage, which I was essentially going to do...I think I need to, not sure...I believe MetaMask uses your password to decrypt the private key and put it into memory...that sounds annoying for the user...I don't think the security risk is that high, we'll see I suppose
- [x] Add tabs to wallet, one tab for wallet itself, one tab for current payout, probably a tab for past payouts
- [x] Allow moving percentages up and down...maybe just toggling on and off for now
- [x] Privacy
 - [x] Potentially explain that Netlify records IP addresses...make sure we are GDPR compliant
 - [x] Explain that the APIs we use may log IP addresses, list each API
 apple is setting a BUNCH of cookies...disclose all cookies potentially?
- [x] Pass as many lighthouse checks as possible
- [x] Figure out finally how to type actions correctly...we want to be able to pass in any action, but have its type inferred correctly from the if statements
- [x] Consider moving all side-effects up to the very edge of the components...each function should just return objects and functions to be executed by the top level...what do you think of that? Sounds like monads
- [x] Add minifying to Zwitterion
- [x] Find out if the Infura APIs can be used commercially, if so switch to using the default provider in ethers
- [x] Add types for ethers.js, switch to ethers.js es module
- [x] Optimize all requests, especially podcast search, pulling ethereum address and email from the feed...we're pulling a ton of those feeds when we do a search
- [x] Be more intelligent with the service worker, perhaps hit the network first and then update the cache...just try to get rid of caching issues if possible...also learn everything about service workers, since you don't know anything really and it's making things difficult
- [x] If payouts are getting failures and retrying with expontential backoff, an
-d the payout interval check kicks in, it will call payout again, and we will have two instances of the payout function going concurrently...that isn't ideal necessarily, but is it okay? We do want the interval check to kick in if the user refreshes the app, but because we persist the redux state, that means the payout will still be ongoing even when it actually isn't...consider this
- [x] Figure out nonces for real, right now I'm just letting exponential backoff take care of the issue, which is messy but should be robust. Follow these issues:
 - [x] ethers-io/ethers.js#346
 - [x] ethers-io/ethers.js#451
- [x] Scroll up when moving between routes...but then you might not be able to go back to the same position you were at...figure that out
- [x] Allow copying public key https://stackoverflow.com/questions/400212/how-do-i-copy-to-the-clipboard-in-javascript
- [x] If there might be issues with using the podcast images from iTunes (perhaps they are promotional materials as described the search api terms), we can always just grab the image from the feed, which should not have anything to do with the iTunes promotional materials if I am not mistaken
- [x] We need to be able to refresh podcasts and episodes...the titles and descriptions might become stale, since we set them once when subscribed to or added to a playlist, and we do not ever update them
- [x] Ask lit-plugin to look at interpolation within css styles, it is causing errors but shouldn't
- [x] Some feeds do not have an image, but the itunes result does...deal with that
- [x] Setting properties from an async custom element creation function doesn't seem to work...at least the router doesn't seem to set them
- [x] Decide how to abstract...custom elements or functions, they both seem to have pros and cons
- [x] Get playlist on Android to work always
 - [x] It seems like on 4G, something happens when episodes get completed. Sometimes this error gets thrown, it might be correlated: Uncaught (in promise) DOMException
- [x] Create a notifications system
- [x] Allow moving forward and backward in playlist from media notification
- [x] Why won't the artwork work on the android media notifications?
- [x] I kind of like my hamburger menu though, it has rounded edges
  - [x] Get rid of hamburger component
- [x] Add back buttons (I might not need this because iOS PWAs will soon have back swipe gestures, and I believe mobile Safari already has back buttons built in)
- [x] Should I be using BigNumber for everything, all calculations? It would be nice to just not worry about all of the rounding errors and get exactly accurate results, but it would also be nice to not to have an unnecessary dependency
- [x] We need to use BigNumber for everything
- [x] Order the wallet items by payout amount or percentage
- [x] Separate the concerns of sending actions and doing the calculations...it would be nice to keep the store dispatches at the top level inside of components...then again, if I ever want to share that functionality, I'd want to abstract it away into a module, which I am already doing
- [x] The router should really have the container code, not the components themselves...they should be embeddable anywhere
- [x] test double audio element to get perfect Android background playlist progression
- [x] Clean up the html on the episode overviews
- [x] Allow playing episodes from the podcast or episode overviews
- [x] Ubuntu font!!!
- [x] Add three dots to playlist items
- [x] Replace hamburger element with icon
- [x] Standardize all css, get rid of all inline styles
- [x] Automated tests...we should get pretty close to formal verification
- [x] Make it look good on desktop
- [x] Unsubscribe from a podcast...remove it and all of its episodes and data...make sure to add a confirmation...perhaps look into that one confirmation web component, or just be simple and use the native confirmation dialog for now
- [x] Use a horizontal three dots...remove episode from playlist, get link to episode in playlist
- [x] A podcast time should never show 60 seconds, only 59 seconds...something off by 1 in the flooring modding and rounding probably
- [x] When should we update persisted podcast and episode information? The titles descriptions etc may become stale
  - [x] Perhaps whenever a podcast overview is viewed, update the information that could have gone stale...the same with an episode
  - [x] If you click subscribe, it should probably do it again as well and refresh the values
- [x] Add a notification system, after clicking subscribe or add to playlist, notify the user
- [x] Optimize feed loading...I load the feed every time from the podcast overview and episode overview so that they can be url addressable without any other information, but it makes things slow because of all of the network round trips. Perhaps figure out some kind of intelligent caching
- [x] Route with the same parameters as other routes will get triggered...right now the episode overview page is loading even on the playlist page
- [x] Get rid of the playlist-specific code in the router
- [x] Adding to the playlist has a bug where the order is messed up
- [x] Podcast started over when it was last in the list
- [x] Figure out a sane way to type actions
- [x] Make an even better logging system that logs everything from the beginning, and will allow users to send me the logs without compromising personal information to help solve issues
- [x] Zero knowledge seemed to be updating everything at double...it had a stop as its first timestamp event, I wonder if that was the issue
- [x] The log needs to be much more efficient, printing the state on each state change uses a LOT of text once you have a lot of info in there
- [x] After each payout condense the timestamps down into a duration
- [x] Allow the user to restore their wallet from mnemonic phrase...right now we instruct them to store it somewhere safe, but we do not allow them to restore their wallet with it
- [x] Add a little refresh button to the balance
- [x] Make sure we can rely on the ETH Gas Station API: https://github.com/ethgasstation/ethgasstation-backend/issues/5
- [x] Consider creating a TheGraph subgraph or whatever to search Podcrypt transactions, which will be marked by data that says "podcrypt.app"
- [x] If there are any issues with the payout for a podcast, we need to notify the user somehow. For each podcast, show indicators of success or failure, perhaps we need a whole page to show what's going on
- [x] Watch out for sharing param names from the router...every time a route changes, all components may update if the query variable names are the same
- [x] Make the menu scrollable, add icons to the menu items?
- [x] Box shadows on lists are not quite perfect, the left side is still there technically, and the bottom does not extend all the way to the right
- [x] Instead of depending on the currentRoute to do logic in each component (like only checking the ethereum account balance whenthe currentRoute is /wallet), set a visible or viewed or currentcomponent property from the router
- [x] Only have the loading thing do the transition when disappearing, not when appearing. It should appear immediately
- [x] Make sure the app is scaling well with many podcasts, episodes, and playlist items
  - [x] We should be careful with calculations that run on any state change, like the wallet does...put in some basic change detection and we should be good
- [x] The seed phrase page should not say loading all the time...use asyncreplace instead of until, that might work
- [x] The player gets in the way of the ui when you click on the keyboard to enter interval and stuff...the player should either disappear or needs to be part of the OS's calculation for what is viewable
- [x] Because payouts take multiple minutes, it would be nice to show an indicator somewhere if a payout is ongoing, that's what we could use the payout ongoing state property for
- [x] Wouldn't it potentially be better to always load player playing based off of whether or not any episodes are playing? Then we do not have to have weird checks for each type of action
- [x] Search results should be addressable, right now if you refresh on the search results page it just displays index.html
- [x] ENS addresses, seems like podcast owners do not like putting the full Ethereum address into their descriptions
- [x] Do not pay out to Podcrypt multiple times...just once per interval, no matter how many times payout now has been clicked, I think I got more payments from myself than I should have
- [x] Fix podcrypt.eth resolver...it got messed up and set to 0x0x somehow...
- [x] Make it work completely offline
- [x] Fix nonces for payouts. Before this feature is officially supported, just implement it yourself: https://github.com/ethers-io/ethers.js/issues/435#issuecomment-467284296
- [x] Split up the reducer into multiple reducers
- [x] Add podcast image to notification
- [x] Make the notification thing better looking
- [x] Toasts when important things happen
- [x] Figure out a better way to include the ubuntu font, comply with the terms of the license, and attribute with our automatic attribution tool
- [x] How I Built this does not load, something seems wrong with passing the feedurl to the proxy, it has a query string in it
- [x] All of the lists should be abstracted into one component if possible
- [x] Get the desktop app to look good
- [x] We need to fix components so that they do not react to other components url changes...I've already done this for the playlist component
- [x] What to do if transactions fail? Into the Ether failed...I think the gas for their contract is too high...who's problem should that be? I want to pay as little gas as possible, it will be difficult if people have contract addresses that require more gas
- [x] Scroll to the top when switching certain views
- [x] Z-indexing on the new lists is off, at least for the podcast list
- [x] Make the menu hit box bigger
- [x] Consider keeping the search results input with the search results
- [x] Improve payout tests...add tests for transaction amounts and balances before and after
- [x] Do not allow the user to scroll the loading screen
- [x] Follow this bug, make sure we don't have easy crashes with downloaded episodes on Chrome for Android: https://bugs.chromium.org/p/chromium/issues/detail?id=967551&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified
- [x] Add duration information on podcast episodes...show the total duration, and how much the user has listened to
- [x] Do not put the warnings up on the wallet immediately...if they want to receive eth in any way, that's where we should put the warnings...create the seed wallet and private key and seed phrase automatically for them, then show it to them there
- [x] Only allow certain podcast and episode dropdown options if they make sense...for example, if you have not subscribed to a podcast, do not show the option of deleting the podcast
- [x] Make sure to be using dompurify correctly: https://github.com/cure53/DOMPurify/issues/344
- [x] Add currently playing title, and potentially other useful information to the top bar
- [x] Redo migrations...they are a mess. We need to have types for every single transition, so 32->33 needs its own types...I think that will solve most of the issues
- [x] One of my manual payouts seemed to pay one of the podcasts way too much...not sure why, but into the Ether got a $9 payout, when Podcrypt get $1, another podcast got $5, and another $.06...it was way too much
- [x] Look into the Google Doc that Podnews shared with you, make sure your episode descriptions are very nice
- [x] Consider rethinking the podcasts search page thing...put the search bar directly in the center of the page, just like the Google homepage. When the user clicks enter, slide the search bar up and show the results right there
- [x] Create a button widget for podcasts to embed a "Play on Podcrypt" thing. Look at examples of other buttons that do this. Provide this from within Podcrypt
- [x] Rearrange icons on rows, make the 3 dots menu huge and on the left
- [x] Downloading, playing, and adding to playlist should probably all be present...make the ... menu bigger
- [x] fix podcrypt.eth resolver...the resolver contract address that I deployed is incorrect for some reason...I need to set it to the correct one (look at lastmjs.eth, that one was done correctly). After I setup the resolver, I can set the address for the resolver to resolve to
- [x] Show the ENSName and the ethereumAddress to the user when the click on the verified button
- [x] Add About button to the main page when the list of podcasts is empty. Make sure the about page is as simple and explanatory as possible
- [x] Add podcasts to the main page, redo the search results, combine it into one page...shomehow
- [x] Create notification system
- [x] Create modal system, get rid of all alerts and confirms and selects
- [x] disable touch events on the main loading screen
- [x] Should all rows be the same size?
- [x] Way too many NaNs on the wallet
- [x] iOS backtracking before 0 the time gets all messed up
- [x] The progress event off of the audio element seems to be really slowing down scrolling on iOS
- [x] The search bar is not centered on iOS
- [x] The number inputs on iOS do not expand much, the width is too small. For example, 1000 shows as 10
- [x] Generate the wallet immediately. In the about page, give podcast owners their Ethereum address to put into their description...perfect easy onboarding. We will then have to explain how to cash out through Coinbase or somewhere else. Maybe Wyre will have some kind of easy cash out solution eventually. Or hopefully Stripe or Fidelity or PayPal will just add Ethereum somehow
- [x] Backing up the state to a json file stopped partway for me...
- [x] Make sure the confirmation prompt still shows up on iOS devices
