### ISSUE TITLE
1.0

### ISSUE THREAD

**Issue by lastmjs** [lastmjs/podcrypt#13]
- [ ] High priority
  - [ ] Wallet should work offline, balance should not show Loading... or NaN if offline, but the last known balance
  - [ ] What do we need to do to educate users on Podcrypt on first load? Do they know what Podcrypt is? Will they understand how donations work?
  - [x] Add a public roadmap to the About page
  - [ ] Improve the Podcrypt wallet like the Sustainus wallet...consider combining them, though I'm not sure the future of Sustainus in light of the new npm funding thing coming out hopefully by the end of September
  - [ ] Get on all of the DApp tracking websites
  - [ ] Create a TheGraph Subgraph for Podcrypt (Join the Hackathon on September 16th)
  - [ ] Debit card purchases with Wyre
  - [ ] Integrate DAI
  - [ ] Integrate Bitcoin
  - [ ] Refactor the wallet to take all of the good things from Sustainus
  - [ ] Payouts must be perfect, with retries and background sync and everything!
  - [ ] Create a system that can handle many -> many relationship between a user's wallet and podcasts (the cryptocurrencies accepted between them)
  - [ ] Robust automated tests for payments
  - [ ] Full wallet with send and receive
  - [ ] Tip individual podcasts
  - [ ] Add weights to podcasts
  - [ ] Consider allowing the user to change the Podcrypt percentage
  - [ ] When we add the ability to send money to someone, why not put that in a modal?
  - [ ] Play and pause and seek listeners for the iOS/iPadOS lock screen player
  - [ ] Value per unit of time can be changed
  - [ ] Percentages to pay out can be changed
  - [ ] One-off donations/tips
  - [ ] If there are any issues with the payout for a podcast, we need to notify the user somehow. For each podcast, show indicators of success or failure, perhaps we need a whole page to show what's going on
- [ ] Medium priority
  - [ ] Fix the loading indicator component...it's kind of weird, and Chrome pushed an update that seemed to break it. I couldn't scroll anywhere
  - [ ] Look into the Google Doc that Podnews shared with you, make sure your episode descriptions are very nice
    - [ ] We need to figure out how to handle content:encoded and markdown
  - [ ] Redo the podcast and episode rows
    - [ ] Rearrange icons on rows, make the 3 dots menu huge and on the left
    - [ ] Downloading, playing, and adding to playlist should probably all be present...make the ... menu bigger
    - [ ] Should all rows be the same size?
    - [ ] Add downloaded size to the episode rows
    - [ ] Duration of episode
  - [ ] Create a notifications system
  - [ ] Drag the playlist instead of arrows
  - [ ] Drag and drop playlist ordering, some with podcasts
  - [ ] Cloud backups
  - [ ] Transfer account information peer-to-peer to another device
  - [ ] Allow everything to be restored from the seed phrase, move the seed phrase recovery out of the wallet and into the backup and restore section
  - [ ] Sometimes when ending an episode, the episode starts over and is not marked as listened for some reasons (this happens relatively often, still happening)
  - [ ] Update podcast ethereum address and ens name correctly in the wallet and everywhere...make sure it stays up to date correctly...for example, in the wallet, the address to display is pulled from the statically saved podcast description
  - [ ] Make sure that the app remembers the last route every single time it loads...sometimes it will reset you to the homepage after a restart, perhaps every time actually
  - [ ] Explain security
  - [ ] Implement extremely high security
    - [ ] CSP
    - [ ] Pass all automated audit tools
    - [ ] Checkin all dependencies, no dynamic installation of node_modules
  - [ ] Only allow certain podcast and episode dropdown options if they make sense...for example, if you have not subscribed to a podcast, do not show the option of deleting the podcast
- [ ] Low priority
  - [ ] FireFox download backup file not working, cuts off short
  - [ ] Media notification listener not working
  - [ ] Clean up numbers and strings, get rid of bignumber in as many places as possible, only use it for eth calculations
  - [ ] Use web.dev as a resource to audit everything
  - [ ] Get RSSParser to be a module that runs without build tools (except bare specifiers)
  - [ ] Study how MetaMask handles private keys...the web3 docs say to never store the private key unencrypted in localStorage, which I was essentially going to do...I think I need to, not sure...I believe MetaMask uses your password to decrypt the private key and put it into memory...that sounds annoying for the user...I don't think the security risk is that high, we'll see I suppose
  - [ ] Implement the nonce manager for managing nonces once ethers.js v5 comes out
  - [ ] Figure out service workers, get everything to work offline always, as much as possible
  - [ ] Pass as many lighthouse checks as possible
  - [ ] More powerful subscriptions (automatic downloads? Notifications when new episodes come in?)
  - [ ] Refactor to plain HTMLElement classes, get rid of functional element
  - [ ] Add minifying to Zwitterion
  - [ ] Add types for ethers.js, switch to ethers.js es module
  - [ ] Be more intelligent with the service worker, perhaps hit the network first and then update the cache...just try to get rid of caching issues if possible...also learn everything about service workers, since you don't know anything really and it's making things difficult
  - [ ] Think about replacing my custom nonce solution with the nonce manager: Fix nonces for payouts. Before this feature is officially supported, just implement it yourself: ethers-io/ethers.js#435 (comment)
  - [ ] Peacefully transition from a streaming episode to a downloaded episode
  - [ ] Very large episodes (Joe Rogan #1309 which is over 2 hours, probably the dan carlin episodes) give us a little bit of trouble. The load and play well, but things seems a bit slow, and when you hit pause the player play/pause button sometimes does not switch correctly)
  - [ ] Speed up downloads maybe (one person has complained that they are really slow)
  - [ ] Scroll up when moving between routes...but then you might not be able to go back to the same position you were at...figure that out
  - [ ] We need to be able to refresh podcasts and episodes...the titles and descriptions might become stale, since we set them once when subscribed to or added to a playlist, and we do not ever update them
  - [ ] Ask lit-plugin to look at interpolation within css styles, it is causing errors but shouldn't
  - [ ] Order the wallet items by payout amount or percentage
  - [ ] Dynamic imports and service worker caching for all elements
  - [ ] Separate the concerns of sending actions and doing the calculations...it would be nice to keep the store dispatches at the top level inside of components...then again, if I ever want to share that functionality, I'd want to abstract it away into a module, which I am already doing
  - [ ] The router should really have the container code, not the components themselves...they should be embeddable anywhere
  - [ ] Clean up the html on the episode overviews
  - [ ] Show indication of episode progress on episode rows
  - [x] Add a public roadmap to the About page
  - [ ] Sometimes downloaded episodes will start pausing every few seconds...and I have to refresh a few times to get it to stop
  - [ ] Perfect background playlist progression...try using the service worker and having one episode loaded only
  - [ ] Allow the donate with Podcrypt button to say Listen With Podcrypt or maybe something else
  - [ ] Background sync downloads and all requests that need to go through no matter what
  - [ ] Deal with strings and numbers like Sustainus does it
  - [ ] Don't set things to loading in the wallet when updating every 30 seconds
  - [ ] We need to figure out something for testing for ENS...the ENS names have to be registered on the test network as well, so we should probably grab the real address from Ethereum main network and then use that on the test network
  - [ ] Look into Netlify's built-in proxying...we might be able to do that instead of running out own proxy
  - [ ] Make sure the marquee is working correctly on all screen sizes, I'm hoping the Chrome simulator thing was just wrong...make sure the text goes all the way out one side and all the way into the other
    - [ ] The scrolling disappearance and reappearance is not consistent across mobile and desktop
    - [ ] Do not freeze the main thread, the marquee lags
    - [ ] Only scroll if the text is too big
  - [ ] The search bar is not centered on iOS
  - [ ] Show the ENSName and the ethereumAddress to the user when the click on the verified button
  - [ ] Look into persistent data: navigator.storage.persist()
  - [ ] Make sure to check that we handle the quota exceeded error gracefully...tell the users what to do
  - [ ] Refactor pc-podcast-search-results completely...
  - [ ] Add the tabindex to the global state so that it is persisted on refreshes
  - [ ] Consider dynamically adding the search results page...and consider not naming the tab search results, but naming it the search term (this can probably wait until 1.0 or 2.0)
  - [ ] Rethink some of the pages that we have going on and see if they can just be modals
  - [ ] We might want to encapsulate the modal system...both of the modals for the podcast and episode rows are very similar
  - [ ] Get the service worker to work immediately on all devices, without requiring a page reload. Claim all clients might be what the api is called
  - [ ] iOS 13 should fix the downloading json file...which kind of works but kind of doesn't...the download attribute apparently doesn't actually work, so a new tab is opened with the file contents instead
  - [ ] Use background fetch and sync appropriately (especially for episode downloads)
  - [ ] Some servers do not expose range headers...the Access-Control-Expose-Headers header in the response from the server may not have a range header...this I believe was causing the drops when streaming that I was experiencing from a Wyre Talks episode. In these cases...we might want to detect that and then stream from our proxy server. I really don't want to start streaming from the proxy server if we don't have to, but it might be the best thing to do in these cases
    - [ ] To test this, on WiFi listen to and then look at the requests for Wyre Talks episode about tbtc, episode 47: https://podcrypt.app/episode-overview?feedUrl=https://feeds.simplecast.com/mvN6wTxg&episodeGuid=65441a21-a26e-411e-b012-056d6621e4a4
  - [ ] Add duration information on podcast episodes...show the total duration, and how much the user has listened to
  - [ ] Make sure to be using dompurify correctly: cure53/DOMPurify#344
  - [ ] Redo migrations...they are a mess. We need to have types for every single 
transition, so 32->33 needs its own types...I think that will solve most of the issues
  - [ ] Figure out a better way to include the ubuntu font, comply with the terms of the license, and attribute with our automatic attribution tool
  - [ ] We need to fix components so that they do not react to other components url changes...I've already done this for the playlist component
  - [ ] Scroll to the top when switching certain views
  - [ ] Make the menu hit box bigger
  - [ ] The player gets in the way of the ui when you click on the keyboard to enter interval and stuff...the player should either disappear or needs to be part of the OS's calculation for what is viewable
  - [ ] Wouldn't it potentially be better to always load player playing based off of whether or not any episodes are playing? Then we do not have to have weird checks for each type of action
  - [ ] Watch out for sharing param names from the router...every time a route changes, all components may update if the query variable names are the same
  - [ ] Instead of depending on the currentRoute to do logic in each component (like only checking the ethereum account balance whenthe currentRoute is /wallet), set a visible or viewed or currentcomponent property from the router
  - [ ] Dynamic imports and service worker caching for all elements
  - [ ] Standardize all css, get rid of all inline styles
  - [ ] When should we update persisted podcast and episode information? The titles descriptions etc may become stale
   - [ ] Perhaps whenever a podcast overview is viewed, update the information that could have gone stale...the same with an episode
     - [ ] If you click subscribe, it should probably do it again as well and refresh the values
  - [ ] http://webpagetest.org
  - [ ] Write whitepaper
  - [ ] We might want to just use the ratechange event on the audio element to listen for playback rate changes instead of manually listening from the select
  - [ ] Change the playback rate select to a custom thing...and allow the user to set their own custom playback rate
-   [x] Get backups to work on iOS, file download just doesn't work for some reason
- [x] Figure out why downloaded episodes stop randomly (this might be fixed already)...the request to the service worker seems to be cancelled by the loadeddata event hitting play on the audio element
- [x] Get very large downloaded episodes to work properly on iOS and Android
- [x] From No Crypto to Know Crypto, downloaded episodes stopped playing at various points...the media notification disappears and the sound stops, episodes 89 and 95
- [x] Do not send transactions one by one. Get rid of the main for loop. Gather statically all of the information necessary to do a payout, including the nonces needed, then execute them consecutively all at once...this may help the double transaction issues. Also, consider building an interface that abstracts away coin and blockchain if possible
- [x] Follow Android playlist in the background on cellular data issues:https://bugs.chromium.org/p/chromium/issues/detail?id=884517&can=2&start=0&num=100&q=Media%20notification&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=
- [x] For background playlist progression, try playing multiple audio elements at once, each element except for the main one will play silence. The silence will be as long as all of the audio element sources before it. Then we can progress in the background, because we will always be playing and never stop
- [x] Entities to receive payouts can be turned on or off before the interval is over
- [x] Explain security
- [x] Add tabs to wallet, one tab for wallet itself, one tab for current payout, probably a tab for past payouts
- [x] test double audio element to get perfect Android background playlist progression
- [x] Add all episodes from a certain point
- [x] Allow podcast and episode embeds...either an iframe or a custom element
- [x] Create a "listen to on Podrypt" or something element that you can share, pull request to Into the Ether
- [x] Switch to storing all audio files as blobs in IndexedDB, instead of arraybuffers. We should be able to do this once the feature is supported in WebKit on iOS. Follow this bug: https://bugs.webkit.org/show_bug.cgi?id=198278
- [x] Allow simultaneous downloads of multiple files, we'll probably have to chunk everything up and use range requests...also, background sync might be necessary to make sure downloads will always continue and finish even if the user puts the app in the background...this should work great on Android, hopefully iOS will catch up
- [x] Optimize all requests, especially podcast search, pulling ethereum address and email from the feed...we're pulling a ton of those feeds when we do a search
- [x] All double-spending issues must be accounted for! I'm not sure why that has happened to me multiple times
- [x] Automated tests, mostly for the time tracking and payments
- [x] If payouts are getting failures and retrying with expontential backoff, an
-d the payout interval check kicks in, it will call payout again, and we will have two instances of the payout function going concurrently...that isn't ideal necessarily, but is it okay? We do want the interval check to kick in if the user refreshes the app, but because we persist the redux state, that means the payout will still be ongoing even when it actually isn't...consider this
- [x] Add a little refresh button to the balance
- [x] Make Podcrypt a viable crypto wallet...add the ability to send funds
- [x] Add Wyre widget
- [x] The seed phrase page should not say loading all the time...use asyncreplace instead of until, that might work
- [x] Search results should be addressable, right now if you refresh on the search results page it just displays index.html
- [x] Fix podcrypt.eth resolver...it got messed up and set to 0x0x somehow...
- [x] Improve payout tests...add tests for transaction amounts and balances before and after
 - [x] fix podcrypt.eth resolver...the resolver contract address that I deployed is incorrect for some reason...I need to set it to the correct one (look at lastmjs.eth, that one was done correctly). After I setup the resolver, I can set the address for the resolver to resolve to
- [x] Arbitrary cryptocurrencies framework
- [x] Switch to blobs for downloads, I think it might be faster to first load into the audio element
- [x] Should we just put the Ethereum receive address page thing in a modal?
- [x] Turn all of the alerts and confirms and menus into custom elements...it's getting a bit messy in there
- [x] Instead of saying no results tell the user to search for podcasts above, just like the my podcasts tab
- [x] Loading for each tab individually...try not to block if possible
- [x] In the about page, give podcast owners their Ethereum address to put into their description...perfect easy onboarding. We will then have to explain how to cash out through Coinbase or somewhere else. Maybe Wyre will have some kind of easy cash out solution eventually. Or hopefully Stripe or Fidelity or PayPal will just add Ethereum somehow
- [x] Once payments are stable, I think the next biggest feature to implement is DAI...we need the marketing and hype that could come from that integration
- [x] The number inputs on iOS do not expand much, the width is too small. For example, 1000 shows as 10
